# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false
before_install:
 - Rscript -e "install.packages('devtools');devtools::install_github(repo = 'pepkit/pepr',ref = 'dev');source('https://bioconductor.org/biocLite.R');biocLite('GenomicRanges');biocLite('BiocFileCache')"
