# This is a faulty PEP.
# The readFunName and readFunPath values point to function that does not exist
metadata:
  sample_table: sample_table.csv

bioconductor:
  readFunName: readBedFiles_missing
  readFunPath: readBedFiles_missing.R
